### ISSUE TITLE
Ini shell script, bukan python script.

### ISSUE THREAD

**Issue by mul14** [firhatsungkar/backup-vscode#1]
Setelah melihat code-nya diawali `#!/bin/bash`, dan code-code lainnya, ini adalah shell script, bukan python script. Jadi alangkah baiknya di-rename dari `.py` menjadi `.sh`.

**Comment by firhatsungkar** [comment]
Roger that, thanks for feed back👍🏼
Will update soon

**Comment by mul14** [comment]
I'm waiting. 😐

**Comment by firhatsungkar** [comment]
Already updated 😬
